### ISSUE TITLE
ValueError: Error when checking input: expected input_12 to have 3 dimensions, but got array with shape (0, 1)

### ISSUE THREAD

**Issue by Darkadia** [nikhiltitus/music-genre-recognition#1]
When trying to run the project with the latests version of keras and tensorflow, the project show the trace 

 Traceback (most recent call last):
  File "genre_classification.py", line 72, in <module>
    main()
  File "genre_classification.py", line 65, in main
    genre_classifier.predict(data_x)
  File "genre_classification.py", line 44, in predict
    output = model.predict(data_x)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_12 to have 3 dimensions, but got array with shape (0, 1)

**Comment by eShini** [comment]
Hi,
I have exactly the same problem as above, with the same Traceback error.
Does it come from the expand function from the array shape for the output : "mel_output=np.expand_dims(mel_output, axis=0)", which could doesn't match with the shape expected from the trained model ?

**Comment by 0xKaizen** [comment]
Hi,
I just found this repo and wanted to try it out in order to make a little personal project.
I have exactly the same problem as above, with the same Traceback error.
Does it come from the expand function from the array shape for the output : "mel_output=np.expand_dims(mel_output, axis=0)", which could doesn't match with the shape expected from the trained model ?
